// ─────────────────────────────────────────────────────────────────────────────
// market_event.dart
//
// PURPOSE: Represents a single news event that occurred during a simulated day.
//          Events are generated by SimulationEngine and stored in MarketProvider.
//          They drive the Events Log screen and the "recent events" section on
//          the Stock Detail screen.
//
// DIFFERENCE FROM EventDefinition:
//   EventDefinition is a reusable template (static data in event_definitions.dart).
//   MarketEvent is a concrete instance — it records what *actually happened*
//   on day N, including the exact impact percentage that was rolled.
// ─────────────────────────────────────────────────────────────────────────────

class MarketEvent {
  /// Which simulated day this event occurred on.
  /// Day 0 = start of game; increments each time the user presses "Next Day".
  final int dayNumber;

  /// The news headline shown prominently in the events log.
  /// e.g. "Nexacor Industries launches orbital data center"
  final String headline;

  /// A 1–2 sentence elaboration shown in the expanded event card.
  final String description;

  /// The ticker of the affected company, or null if this was a global market
  /// event that affected all stocks simultaneously.
  final String? affectedTicker;

  /// The sector affected by this event, or null if it's a specific company
  /// event or a global event. Used for filtering in the events log.
  final String? affectedSector;

  /// The actual percentage applied to the stock price(s) this day.
  /// Positive = price went up, negative = price went down.
  /// e.g. +8.5 means the stock's price increased by 8.5%.
  final double impactPercent;

  /// Whether this event had a positive (bullish) or negative (bearish) effect.
  /// Derived from impactPercent, but stored explicitly for fast UI coloring
  /// without needing to check the sign of impactPercent everywhere.
  final bool isPositive;

  /// Whether this event affected ALL stocks (global) vs a specific ticker/sector.
  final bool isGlobal;

  /// Wall-clock time when this event was generated.
  final DateTime timestamp;

  const MarketEvent({
    required this.dayNumber,
    required this.headline,
    required this.description,
    required this.affectedTicker,
    required this.affectedSector,
    required this.impactPercent,
    required this.isPositive,
    required this.isGlobal,
    required this.timestamp,
  });

  // ── Serialisation ───────────────────────────────────────────────────────────

  Map<String, dynamic> toJson() {
    return {
      'dayNumber': dayNumber,
      'headline': headline,
      'description': description,
      // nullable fields — JSON null is valid
      'affectedTicker': affectedTicker,
      'affectedSector': affectedSector,
      'impactPercent': impactPercent,
      'isPositive': isPositive,
      'isGlobal': isGlobal,
      'timestamp': timestamp.toIso8601String(),
    };
  }

  factory MarketEvent.fromJson(Map<String, dynamic> json) {
    return MarketEvent(
      dayNumber: json['dayNumber'] as int,
      headline: json['headline'] as String,
      description: json['description'] as String,
      affectedTicker: json['affectedTicker'] as String?,
      affectedSector: json['affectedSector'] as String?,
      impactPercent: (json['impactPercent'] as num).toDouble(),
      isPositive: json['isPositive'] as bool,
      isGlobal: json['isGlobal'] as bool,
      timestamp: DateTime.parse(json['timestamp'] as String),
    );
  }

  @override
  String toString() =>
      'MarketEvent(day $dayNumber: "$headline" [${impactPercent.toStringAsFixed(1)}%])';
}
